/*
SQLyog Ultimate v12.08 (64 bit)
MySQL - 5.6.29 
*********************************************************************
*/
/*!40101 SET NAMES utf8 */;

insert into `t_flow_scene_activity` (`activity_id`, `activity_name`, `activity_file_name`, `create_user_id`, `create_date`, `modify_user_id`, `modify_date`, `activity_rule`, `status`) values('1','大转盘','HomePage,RoundAboutModule,trailerRedTraffic',NULL,'0000-00-00 00:00:00',NULL,'0000-00-00 00:00:00','1.活动时间：2016-05-01 10:000 至 2016-08-01\r\n2.活动时间内得累计赠送200G流量，赠完为止。\r\n3.每个用户最高可获得200M，每天可以参与一次大抽奖。\r\n4.号码处于欠费停机状态均不能参加活动。请确保手机处于正常状态，否则运营商可能会充值失败。\r\n5.联通纯2G,3G用户，未实名认证用户以及单一流量规格包叠加超过5次会充值实效，符合此条件用户建议使用其他手机号参与活动。\r\n6.抢到的流量将在24小时内充值到手机号码中，请留意短信通知，当月有效，江西省内可用，且有限使用该赠送流量。\r\n7.本次活动移动，联通，电信，江西省内用户均可参与，若出现兑奖异常，请及时给客服留言寻求帮助。\r\n8.如果你喜欢本次活动，请在右上角为我们活动点赞。',NULL);
insert into `t_flow_scene_activity` (`activity_id`, `activity_name`, `activity_file_name`, `create_user_id`, `create_date`, `modify_user_id`, `modify_date`, `activity_rule`, `status`) values('2','摇一摇','HomePage,FlowShakeModule,trailerRedTraffic',NULL,'0000-00-00 00:00:00',NULL,NULL,'1.活动时间：2016-05-01 10:000 至 2016-08-01\r\n2.活动时间内得累计赠送200G流量，赠完为止。\r\n3.每个用户最高可获得200M，每天可以参与一次大抽奖。\r\n4.号码处于欠费停机状态均不能参加活动。请确保手机处于正常状态，否则运营商可能会充值失败。\r\n5.联通纯2G,3G用户，未实名认证用户以及单一流量规格包叠加超过5次会充值实效，符合此条件用户建议使用其他手机号参与活动。\r\n6.抢到的流量将在24小时内充值到手机号码中，请留意短信通知，当月有效，江西省内可用，且有限使用该赠送流量。\r\n7.本次活动移动，联通，电信，江西省内用户均可参与，若出现兑奖异常，请及时给客服留言寻求帮助。\r\n8.如果你喜欢本次活动，请在右上角为我们活动点赞。',NULL);
insert into `t_flow_scene_activity` (`activity_id`, `activity_name`, `activity_file_name`, `create_user_id`, `create_date`, `modify_user_id`, `modify_date`, `activity_rule`, `status`) values('3','刮刮乐','HomePage,ScratchModule,trailerRedTraffic',NULL,'0000-00-00 00:00:00',NULL,NULL,'1.活动时间：2016-05-01 10:000 至 2016-08-01\r\n2.活动时间内得累计赠送200G流量，赠完为止。\r\n3.每个用户最高可获得200M，每天可以参与一次大抽奖。\r\n4.号码处于欠费停机状态均不能参加活动。请确保手机处于正常状态，否则运营商可能会充值失败。\r\n5.联通纯2G,3G用户，未实名认证用户以及单一流量规格包叠加超过5次会充值实效，符合此条件用户建议使用其他手机号参与活动。\r\n6.抢到的流量将在24小时内充值到手机号码中，请留意短信通知，当月有效，江西省内可用，且有限使用该赠送流量。\r\n7.本次活动移动，联通，电信，江西省内用户均可参与，若出现兑奖异常，请及时给客服留言寻求帮助。\r\n8.如果你喜欢本次活动，请在右上角为我们活动点赞。',NULL);
insert into `t_flow_scene_activity` (`activity_id`, `activity_name`, `activity_file_name`, `create_user_id`, `create_date`, `modify_user_id`, `modify_date`, `activity_rule`, `status`) values('4','老虎机','HomePage,Slotmachine,trailerRedTraffic',NULL,'0000-00-00 00:00:00',NULL,NULL,'1.活动时间：2016-05-01 10:000 至 2016-08-01\r\n2.活动时间内得累计赠送200G流量，赠完为止。\r\n3.每个用户最高可获得200M，每天可以参与一次大抽奖。\r\n4.号码处于欠费停机状态均不能参加活动。请确保手机处于正常状态，否则运营商可能会充值失败。\r\n5.联通纯2G,3G用户，未实名认证用户以及单一流量规格包叠加超过5次会充值实效，符合此条件用户建议使用其他手机号参与活动。\r\n6.抢到的流量将在24小时内充值到手机号码中，请留意短信通知，当月有效，江西省内可用，且有限使用该赠送流量。\r\n7.本次活动移动，联通，电信，江西省内用户均可参与，若出现兑奖异常，请及时给客服留言寻求帮助。\r\n8.如果你喜欢本次活动，请在右上角为我们活动点赞。',NULL);
insert into `t_flow_scene_activity` (`activity_id`, `activity_name`, `activity_file_name`, `create_user_id`, `create_date`, `modify_user_id`, `modify_date`, `activity_rule`, `status`) values('5','砸金蛋','HomePage,SmashingGoldenEggs,trailerRedTraffic',NULL,'0000-00-00 00:00:00',NULL,NULL,'1.活动时间：2016-05-01 10:000 至 2016-08-01\r\n2.活动时间内得累计赠送200G流量，赠完为止。\r\n3.每个用户最高可获得200M，每天可以参与一次大抽奖。\r\n4.号码处于欠费停机状态均不能参加活动。请确保手机处于正常状态，否则运营商可能会充值失败。\r\n5.联通纯2G,3G用户，未实名认证用户以及单一流量规格包叠加超过5次会充值实效，符合此条件用户建议使用其他手机号参与活动。\r\n6.抢到的流量将在24小时内充值到手机号码中，请留意短信通知，当月有效，江西省内可用，且有限使用该赠送流量。\r\n7.本次活动移动，联通，电信，江西省内用户均可参与，若出现兑奖异常，请及时给客服留言寻求帮助。\r\n8.如果你喜欢本次活动，请在右上角为我们活动点赞。',NULL);
insert into `t_flow_scene_activity` (`activity_id`, `activity_name`, `activity_file_name`, `create_user_id`, `create_date`, `modify_user_id`, `modify_date`, `activity_rule`, `status`) values('6','幸运大抽奖','HomePage,TigerRoundModule,trailerRedTraffic',NULL,'0000-00-00 00:00:00','175','2016-06-22 14:57:08','1.活动时间：2016-05-01 10:000 至 2016-08-01\r\n2.活动时间内得累计赠送200G流量，赠完为止。\r\n3.每个用户最高可获得200M，每天可以参与一次大抽奖。\r\n4.号码处于欠费停机状态均不能参加活动。请确保手机处于正常状态，否则运营商可能会充值失败。\r\n5.联通纯2G,3G用户，未实名认证用户以及单一流量规格包叠加超过5次会充值实效，符合此条件用户建议使用其他手机号参与活动。\r\n6.抢到的流量将在24小时内充值到手机号码中，请留意短信通知，当月有效，江西省内可用，且有限使用该赠送流量。\r\n7.本次活动移动，联通，电信，江西省内用户均可参与，若出现兑奖异常，请及时给客服留言寻求帮助。\r\n8.如果你喜欢本次活动，请在右上角为我们活动点赞。',NULL);
